### ISSUE TITLE
Proposal: input param for generate version between current and next major

### ISSUE THREAD

**Issue by lansman** [bndr/pipreqs#22]
I'd like if there is input param that makes requirements not like:
aaa==0.0.1
bbb==1.1.0
ccc==2.0.0

but like:
aaa>=0.0.1,<1.0.0
bbb>=1.1.0,<2.0.0
ccc>=2.0.0,<3.0.0

**Comment by littmus** [comment]
I think this can be done by using import statement with comment. like
```python
import abc #>=0.0.1, <1.0.0
```
Any other idea?

**Comment by audiofeature** [comment]
I would make it simpler, just providing an optional flag to pipreqs that changes == into >=

**Comment by 9cloud** [comment]
Right but that would do it to all of your imports, instead of conditionally. It could be of some use to small projects who can rely on that and just are an addon to something else.

But in that case... wouldn't it be 'better' to just keep it out of code, a do a find-and-replace on the generated file?

**Comment by alan-barzilay** [comment]
Feature implemented in PR#239 as ~=
