### ISSUE TITLE
Release new version for --mode option

### ISSUE THREAD

**Issue by mapattacker** [bndr/pipreqs#240]
Hi, I wonder if it's possible to release a new version for the recent pull request #239, that was merged to master a week back, so that my team can start using it?

Appreciate the help. Thanks!

**Comment by alan-barzilay** [comment]
Hi! Since I'm a new (and apparently the only) maintainer  there are still a few things to setup, such as access to PyPi. While this is not setup I can't make a new release :(
I know this is frustrating and I'm sorry about it, I will try to make a new release as soon as possible but in the mean time cloning the repo and installing it locally is probably your best bet

**Comment by mapattacker** [comment]
Hi :) Thanks for explaining. No problem! Appreciate u taking up the mandate to support this library too.
