### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 10761: character maps to <undefined>

### ISSUE THREAD

**Issue by ickqy** [bndr/pipreqs#266]
Im trying to create a requirements.txt file, but every single time ive tried ive gotten this output

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 10761: character maps to <undefined>`

Ive tried every single way i could fix this but nothing, can someone help? thx :)

**Comment by wasi-master** [comment]
Same error

**Comment by jvhdis** [comment]
I get the same error too.

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4844: character maps to <undefined>`

**Comment by JonasHach** [comment]
Similar error for me

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 81: invalid start byte

**Comment by isaac43** [comment]
Use  --encoding utf-8 in the command

**Comment by alan-barzilay** [comment]
I believe this is a duplicate from #241, I have already devised a fix that enforces utf-8 as the default but I havent had the time to implement it yet. I will be closing this issue since it seems to be solved given the number of likes isaac43 received. Feel free to reopen the issue f the problem persists
