### ISSUE TITLE
Optionally omit package version from requirements file

### ISSUE THREAD

**Issue by jonafato** [bndr/pipreqs#94]
Developers don't always want to include pinned dependencies in the output generated by `pipreqs` (e.g. when using it in conjunction with `pip-compile` from https://github.com/jazzband/pip-tools). `pipreqs` should have a `--no-pin` option to omit versions when desired.

**Comment by troyhoffman** [comment]
Pip freeze always stores the version, but I like the idea of being able to omit the versions.

**Comment by bersbersbers** [comment]
It seems this has been implemented already, but I wanted to add another suggestion. I would find it helpful, even when omitting package versions, to indicate which version I have used. So my ideal output would be using `>=` rather than `==`, still using the version number I have installed. This gives you the best of both worlds: You are not forcing any installer to an old version, but you still transmit the information which (old) version worked for you.

**Comment by alan-barzilay** [comment]
Everything suggested here seems to have been implemented already, closing
